theme: jekyll-theme-hacker
title : Tactical Shield
am_link: https://forums.alliedmods.net/showthread.php?t=303333
issues: https://github.com/Keplyx/TacticalShield/issues
cvars: https://github.com/Keplyx/TacticalShield/blob/master/csgo/cfg/sourcemod/tacticalshield.cfg
owner: https://keplyx.github.io/index.html
